INSERT INTO computerlist VALUES ('LIBP1-LIB001', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB002', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB003', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB004', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB005', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB62', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB63', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB64', 0 ); //
INSERT INTO computerlist VALUES ('LIBP1-LIB65', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB66', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB67', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB68', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB018', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB019', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB020', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB021', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB022', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB013', 0 ); //
INSERT INTO computerlist VALUES ('LIBP1-LIB014', 0 ); //
INSERT INTO computerlist VALUES ('LIBP1-LIB015', 0 ); //
INSERT INTO computerlist VALUES ('LIBP1-LIB016', 0 ); //
INSERT INTO computerlist VALUES ('LIBP1-LIB017', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB025', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB026', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB027', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB028', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB034', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB035', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB041', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB042', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB037', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB043', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB044', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB038', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB045', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB039', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB040', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB048', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB047', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB046', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB036', 0 );
INSERT INTO computerlist VALUES ('LIBP1-LIB031', 0 );
